# Matching jekyll documentation layout
# https://jekyllrb.com/docs/configuration/
# https://jekyllrb.com/docs/configuration/default/

#  ---------- Folder structure:
# https://halfelf.org/2015/jekyll-collections/
source: .
layouts_dir: _jekyll/_layouts
includes_dir: _jekyll/_includes
data_dir: _jekyll/_data
# Collections
collections_dir: collections
collections:
  kb:
    output: true

# ---------- Handling reading
encoding: "utf-8"
markdown_ext: "md"

# ---------- Filtering Content

# ---------- Plugins

# ---------- Conversion
markdown: kramdown
highlighter: rouge

# ---------- Serving
port: 3000
host: localhost

# ---------- Outputting

# ---------- Pagination=
paginate: 5
paginate_path: "/blog/page:num"

# ---------- Default front matters
defaults:
  # All files
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  # Posts
  - scope:
      path: ""
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  # KB articles
  - scope:
      path: ""
      type: "kb"
    values:
      layout: "kb_article"

# ---------- SASS
sass:
  # custom folder path. Default is {source}/_sass
  sass_dir: _jekyll/_sass
  # CSS output style. Valid values are
  # - nested
  # - compact
  # - expanded
  # - compressed
  # https://web-design-weekly.com/2014/06/15/different-sass-output-styles/
  style: compressed
